### ISSUE TITLE
السلام عليكم

### ISSUE THREAD

**Issue by zakisoft2015** [awssat/kleeja#1]
حضرتك انا ركبت الاسكربت لكن لما احاول ارفع ملف 

c:\fakepath\asd.rar

ده بيظهر بعد اختيار الملف و بعد الرفع لا يعطى رابط و لا اجد الملف مرفوع

**Comment by zakisoft2015** [comment]
حضرتك لما بغير فى احجام الامدادات مش بيرفع بالاحجام الجديدة بمعنى غيرت حجم امداد
 ( rar )
 و خليته 1 جيجا و جربت مش بيرفع لكن لو رفعت حجم صغير يرفعه

**Comment by jaafer77** [comment]
عدل على ملف php.ini  في السيرفر لتغيير احجام الملفات

في أحد، ٢١ كانون الثاني، ٢٠١٨ في ١٢:٠٧ م، كتب zakisoft2015 <
notifications@github.com>:

**Comment by jaafer77** [comment]
في أحد، ٢١ كانون الثاني، ٢٠١٨ في ١٢:١٠ م، كتب Jaafer Hassan <
j.redwind@gmail.com>:

**Comment by zakisoft2015** [comment]
الف شكر لحضرتك

انا فعلا عدلت لكن لما حاولت ارفع ملف بصيغة 
rmvb
ظهرت الرسالة دى
تعليمات
: نظام كليجا اكتشف أن الملف
 "Grown-ish.S01E02.720p.rmvb" 
غير آمن ويحتوي على أكواد خبيثه
 .. !!

**Comment by jaafer77** [comment]
عفوا اخي الكريم
هل نصبت اضافة فحص ملفات كليجا سابقا؟

في أحد، ٢١ كانون الثاني، ٢٠١٨ في ٩:٣٣ م، كتب zakisoft2015 <
notifications@github.com>:

**Comment by zakisoft2015** [comment]
السلام عليكم اخى الكريم
هذه هى الاضافت التى تم تثبيتها مع اخر اصدار  و هى نزلة مع النسخة

 kj_download_speed_limit
Limit files download speed for each group 

 kj_ban_admin
Ban a user after so many invalid login attempts to Kleeja control panel 

 language_switch
A language switch box in the top of every page

**Comment by jaafer77** [comment]
ادخل مجلد uploads  في ملف htaccess افتحه وابحث عن صيغة rmvb هل هي موجودة ام
لا اذا كانت موجودة احذفها

في اثنين، ٢٢ كانون الثاني، ٢٠١٨ في ١٠:٠١ ص، كتب zakisoft2015 <
notifications@github.com>:

**Comment by zakisoft2015** [comment]
غير موجوده

# Htaccess for Protection
# Kleeja 2007 - 2010
# $Id: .htaccess 1557 2010-08-08 10:09:50Z saanina $

<Files ~ "^.*\.(php|php*|cgi|pl|phtml|shtml|sql|asp|aspx)">
    Order allow,deny
    Deny from all
</Files>

#Disable PHP engine in this folder
<IfModule mod_php4.c>
php_flag engine off
</IfModule>

#Disable PHP engine in this folder
<IfModule mod_php5.c>
php_flag engine off
</IfModule>

#Don't handle those types in this folder
RemoveType .php .php* .phtml .pl .cgi .asp .aspx .sql

#404 error should show something usefull
#todo/ images->image info, another show our info page
ErrorDocument 404 ../images/not_exists.jpg

**Comment by zakisoft2015** [comment]
max_execution_time 
max_input_time
max_input_vars
memory_limit
post_max_size
session.gc_maxlifetime
upload_max_filesize

حضرتك الاعدادت دى اعملها ايه فى حين ان انا عايز ارفع ملف 10 جيجا ايه انسب اعدادات له

**Comment by jaafer77** [comment]
حسب حقول ملفات التحميل اذا كنت تريد ترفع ١٠ جيجا لازم upload size file يصير
١٠ جيجا وال max upload ١٠٠ جيجا اذا كنت مفعل ١٠ حقول تحميل وهكذا الmax هو
حجم الملفات الكلي في حقول التحميل كلها  file size هو حجم الحقل الواحد

اما بخصوص انو الملف ضار او خبيث حاول تغير اسم الملف وترفعه

في اثنين، ٢٢ كانون الثاني، ٢٠١٨ في ١٠:٢٦ ص، كتب zakisoft2015 <
notifications@github.com>:

**Comment by abdumu** [comment]
المسار c:\fakepath\ 
مجرد مسار تخيلي كمظهر للزائر

**Comment by animeloki** [comment]
السلام عليكم المرجو المساعدة انا ركبت السكريبت لكن عندما اريد تسجيل الدخول املىء البيانات و دئما ما يقول لي كود الامان خاطئ و انا اضعه صحيح ؟؟؟
