### ISSUE TITLE
Where we can buy kleeja plugins? 

### ISSUE THREAD

**Issue by fileiraq** [awssat/kleeja#10]
Please add kleeja plugins so we can download or buy.

**Comment by munjoob** [comment]
https://khamsat.com/programming/php-programming/817539-%D8%A8%D8%B1%D9%85%D8%AC%D8%A9-%D8%A7%D8%B6%D8%A7%D9%81%D8%A9-%D9%84%D8%B3%D9%83%D8%B1%D9%8A%D8%A8%D8%AA-%D9%83%D9%84%D9%8A%D8%AC%D8%A7
