### ISSUE TITLE
مشكلة في اضافة ftp

### ISSUE THREAD

**Issue by Gulfupload** [awssat/kleeja#12]
‏السلام عليكم 
عندي مشكله في اضافة ftp
بحاول اضيف حساب ftp 
بعد الاضافة بحاول ارفع ملف بيعطيني خطأ
الحساب الاف تي بي هو لخدمة تخزين سحابي 
والبورت المستخدم هو 3268

ودي صورة من الخطأ اللي بيظهر

https://t.co/13axQBVKD4‎

**Comment by Gulfupload** [comment]
دا رابط الصورة . بيظهر خطأ

https://gulfupload.com/do.php?img=70712

**Comment by abdumu** [comment]
لا ارى مشكلة
تاكد من اعدادات الحساب وربطة
