### ISSUE TITLE
السكريبت يتم تطويره ببطء

### ISSUE THREAD

**Issue by munjoob** [awssat/kleeja#13]
السكريبت يتم تطويره ببطء
هل لديكم خطة لبيع دومين kleeja.com
كم المطلوب

**Comment by abdumu** [comment]
مرحبا

لايوجد خطة بيع
اذا كان لديك عرض فاكتبه

بالتوفيق

**Comment by munjoob** [comment]
المشكلة السكريبت غير ربحي
لدي فقط رغبة في تطويره بصيغة جديدة
ليس لدي الكثير من المال 
الأمر عندكم فإذا لم يكن هناك نية لديكم للاستمرار في تطويره يمكنني شراء الدومين
أما إذا كانت هناك نية لتطويره فأنتم أدرى بأنفسكم والله هو العالم بالنيات

**Comment by munjoob** [comment]
يمكنني أن أدفع 300$

**Comment by abdumu** [comment]
شكرا لاهتمامك

**Comment by munjoob** [comment]
لم أحصل على جواب واضح

**Comment by abdumu** [comment]
مرحباً،

التطوير الحالي هو لاصلاح اخطاء وضبط المشاكل ولاضافة مميزات جديدة يمكن دائماً انشاء اضافة جديدة خاصة.

اذا وجدت مشكلة فمستودع الكود مفتوح للجميع، قم بعمل بي ار وساقبلها بصدر رحب.


عند وجود اخطاء قوية يتم اصدار نسخة جديدة، وعند وجود اخطاء عادية فيتم تجميع عدة اصلاحلات قبل الاصدار



بالتوفيق

**Comment by munjoob** [comment]
المشكلة ليس بالتطوير يمكن أن تنشأ سكريبت  جديد انطلاقا من كليجا باسم جديد وتضيف ما تريد
الفكرة حول الاستمرار في تطوير سكريبت عربي وزيادة تألقه هذا كل ما في الأمر
السكريبت عمره الآن 11 سنة وهو يستحق أكثر من مجرد اصلاح أخطاء بسيطة هنا وهناك
على كل حال إذا فكرت ببيع الدومين أو لديك سعر معين يمكن أن تطلبه الموضوع مفتوح للنقاش
