### ISSUE TITLE
لا استطيع تسجيل الخروج

### ISSUE THREAD

**Issue by MohamedKaram22** [awssat/kleeja#14]
عندما اضعط تسجيل الخروج
يظهر تم تسجيل الخروج بنجاح
ولكن يعود وكأني مسجل
وعند انشاء عضوية جديدة من جهاز اخر
يظهر تم تسجيل الدخول بنجاح
لكن بعدها يظل كزائر

**Comment by abdumu** [comment]
تاكد من اعدادات الكوكيز، راجع منتدى ترايدنت
