### ISSUE TITLE
عند تحميل الملفات

### ISSUE THREAD

**Issue by MohamedKaram22** [awssat/kleeja#15]
![image](https://user-images.githubusercontent.com/37338484/37400704-ccd17b52-2796-11e8-9674-6d767f85ed5a.png)
تظهر هذه المشكلة عند تحميل اي ملف
او صورة

**Comment by munjoob** [comment]
هناك خطأ في تنفيذ كود php

**Comment by abdumu** [comment]
اذا كانت لديك تعديلات او اضافات فعطلها
اذا كانت نسختك قديمة فحدثها.
