### ISSUE TITLE
مشكلة في احصائيات المركز

### ISSUE THREAD

**Issue by 0nader** [awssat/kleeja#16]
السلام عليكم ورحمة الله وبركاتة

يوجد لدي مشكلة عجيبة ظهرت فجئه في إحصائيات المركز صاير لخبطة

المفترض ان عداد اليوم يتصفر لكي يظهر لي عدد ماتم رفعه على المركز لكن صايرة العدد يزيد شوف الصورة

https://www.traidnt.net/vb/attachment.php?attachmentid=795342&stc=1&d=1521605729

شاكر لكم..

**Comment by 0nader** [comment]
https://www.traidnt.net/vb/attachment.php?attachmentid=795342&stc=1&d=1521605729

**Comment by abdumu** [comment]
رقم نسختك ؟

**Comment by 0nader** [comment]
2.3

**Comment by abdumu** [comment]
fixed
