### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by Kadantte** [awssat/kleeja#17]
Where can i find Kleeja Plugins ?!!!

i trythat : http://kleeja.com/market/plugins ; but the link is down ?!!!

**Comment by abdumu** [comment]
It's included in plugins folder by default with the last version.

**Comment by Kadantte** [comment]
i fined it but Multi FTP plugins is not there

**Comment by abdumu** [comment]
It will be included with Kleeja soon.

**Comment by Kadantte** [comment]
Thank's a Lot :D

**Comment by Kadantte** [comment]
In the last patch I didn't find FTP plugin :/ as u said the plugin gonna be soon, anyway I hope that u including it soon
