### ISSUE TITLE
مشكلة كود الامان خاطىء

### ISSUE THREAD

**Issue by 3bbady** [awssat/kleeja#18]
السلام عليكم و رحمه الله و بركاته
اخى الكريم انا استعمل الاسكربت منذ سنوات
و الان قمت بتركيب اخر اصدار على موقع جديد
الاصدار ٢.٣
لكن تواجهنى مشكلة اثناء تسجيل الدخول
يظهر رسالة بان كود الامان خاطىء
هل يوجد طريقة لالغاء كود الامان و الدخول الى لوحة التحكم
الرجاء الافادة
و هذا رابط الموقع
http://www.9lqh.com

**Comment by abdumu** [comment]
fixed
