### ISSUE TITLE
النظام لا يقبل البريد الإلكتروني ذات الإمتدادات الجديدة!

### ISSUE THREAD

**Issue by alidotworks** [awssat/kleeja#19]
السلام عليكم و رحمة الله و بركاته

القائمين على منظومة "كليجا" المحترمين...

النظام لا يقبل الإمتداد
.works
عند التعديل على البريد الإلكتروني داخل صفحة التحكم

وبالمقابل يقبل بعض الإمتدادات مثل:
com , net , org , info , ae , sa , kw , co , cc , **qt**

مع العلم بأنه لا يوجد إمتداد بإسم:
qt !!

ملاحظة:
النظام قبل الإمتداد
works
في بداية تنصيه.

و دمتم سالمين

**Comment by abdumu** [comment]
مرحباً، 
حاولت أجرب لكن ماطلع معي خطأ، أنت تسخدم آخر نسخة؟

**Comment by alidotworks** [comment]
مرحبتين كبار،

اي نعم. آخر نسخة و هي 2.4.

capture:
[https://ibb.co/fMhZ4H](https://ibb.co/fMhZ4H)
