### ISSUE TITLE
نصائح لجعل السكربت قوي

### ISSUE THREAD

**Issue by momkin** [awssat/kleeja#2]
مرحباً ،،

عندي نصيحتين لجعل السكربت قوي ،،

اولهم اضافة خاصية تعدد الخوادم في حالة امتلاء خادم يتم اضافة خادم جديد بدون عناء

الشيئ الثاني وضع المرفوعات بعدة مجلدات وليس مجلد واحد لان هذا مرهق ولا ينصح به

**Comment by jaafer77** [comment]
جميع ماتكلمت عنه موجود على شكل اضافات مدفوعة في متجر كليجا وهو مغلق الان

في ثلاثاء، ٢٣ كانون الثاني، ٢٠١٨ في ١٢:٥٢ ص، كتب momkin <
notifications@github.com>:

**Comment by abdumu** [comment]
قم بالتبليغ عن اخطاء هنا.

اما لو اردت مميزات فيمكنك التعديل واضافتها كبول ريكويست وسنقوم بقبوله في الكود الاساسي.
