### ISSUE TITLE
مشكلة صغيرة

### ISSUE THREAD

**Issue by MitanOmar** [awssat/kleeja#26]
السلام
عند محاولة تفعيل احد الستايلات ، والتي تتطلب وجود اضافات برمجية خاصة بها
يقوم كليجا بالتحقق من اسم التطبيق فقط في قاعدة البيانات . 
ولكن السكريبت لا يتحقق اذا كانت الاضافة مفعلة ام لا 
في المسار التالي :
Includes/adm/m_style.php 
السطر رقم 75
نحتاج للاضافة الى جملة التحقق من قاعدة البيانات 
"plg_disabled" .
 وبعدها جملة شرطية للتحقق اذا كانت مفعلة ام لا
ولك جزيل الشكر على صنيعك :-)

**Comment by abdumu** [comment]
مرحباً @MitanOmar 

فيك حيل تعدل وتعمل بوش ركويست ؟

**Comment by MitanOmar** [comment]
done !!

**Comment by abdumu** [comment]
thank you 👌
