### ISSUE TITLE
تظليل كود الصوره

### ISSUE THREAD

**Issue by leech24** [awssat/kleeja#28]
النسخه القديمه
اسهل في تظليل كود الصوره

بمجرد الضغط يتم التظليل اوتو

**Comment by abdumu** [comment]
هذا لان تصميم الستايل الجديد يمنع ذلك.
عموما ستايل كليجا موجود في مجلد ادمن ويمكنك التعديل عليه او انشاء ستايل جديد مبني عليه وارفاقة لنا لوضعه في النسخ القادمة

شكرا لك
