### ISSUE TITLE
عند إضافة ملفات تحديث 2.4 لا يعمل مركز التحميل ولا أستطيع الترقية!

### ISSUE THREAD

**Issue by asbahi-m** [awssat/kleeja#29]
السلام عليكم ورحمة الله.

أحاول ترقية إصدار مركز التحميل عندي إلى الإصدار الأخير 2.4، وكلما أضيف ملفات التحديث وأحاول ترقية المركز:
http://www.feqhup.com/install/update.php
تظهر لي صفحة خطأ..

وكلما أردت الدخول إلى صفحات المركز أو لوحة التحكم تظهر لي هذه الأخطاء:
Fatal error: Can't use function return value in write context in /home/up/public_html/ucp.php on line 77
Fatal error: Can't use function return value in write context in /home/up/public_html/go.php on line 145 
Fatal error: Can't use function return value in write context in /home/up/public_html/admin/index.php on line 63

فآمل فضلاً توضيح سبب الإشكال، وكيف نعالجه؟

مع أني قمت بترقية المركز في جهازي المحلي local عبر appserv واشتغل التحديث والمركز طبيعي، الإشكال حاصل معي في الموقع، وهذا رابط الموقع:
http://www.feqhup.com

**Comment by abdumu** [comment]
ما اصدار  اتش بي لديك ؟
وهل حدثت كافة الملفات لاخر نسخة كليجا؟

**Comment by asbahi-m** [comment]
PHP version: 5.6.30

وهي نفس نسخة php للـ آب سيرف

ونعم، أضفت جميع ملفات التحديث.

**Comment by asbahi-m** [comment]
وحاولت أيضاً تركيب السكربت kleeja-master أيضاً ولم يفلح الأمر.. تظهر لي صفحة خطأ.

وهذا هو ملف php.ini إذا حابب تشوف إذا فيه مشكلة.
[php.zip](https://github.com/awssat/kleeja/files/2503570/php.zip)

يعطيك ألف عافية أخوي، بانتظار إفادتكم.

**Comment by abdumu** [comment]
استخدم  php 7 
واخبرني ماذا يحدث. لاحظ ان كليجا لاتدعم حاليا اي اصدار اقل من ٧

**Comment by asbahi-m** [comment]
طيب أخي الفاضل، سنقو بترقية الإصدار إلى 7.. وسأخبرك بالنتيجة.

**Comment by asbahi-m** [comment]
قمنا بالترقية إلى PHP70، واشتغل مركز التحميل بصورة طبيعية.

فقط تبقت مشكلة واحدة عند الدخول إلى:
www.feqhup.com/install/update.php

تظهر صفحة الخطأ:
Internal Server Error 500

وكذلك الأمر بالنسبة لتنصيب كليجا من جديد
www.feqhup.com/kleeja-master/install/install.php
تظهر نفس صفحة الخطأ.

**Comment by abdumu** [comment]
سيظهر الخطأ في لوق الأخطاء.

**Comment by asbahi-m** [comment]
هذا هو الخطأ الذي يظهر لي أخي الحبيب:
[Thu Oct 25 19:39:47.911107 2018] [:error] [pid 17461:tid 139857942771456] [client 37.125.40.161:50071] SoftException in Application.cpp:388: UID of script "/home/up/public_html/kleeja-master/install/install.php" is smaller than min_uid

**Comment by abdumu** [comment]
اعتقد مشكلة صلاحيات.

غير صلاحيات الملف واخبرني بالنتيجة

**Comment by asbahi-m** [comment]
فعلاً أخي الحبيب المشكلة في الصلاحيات..

يعطيك العافية، تم ترقية المركز بنجاح.

**كل الشكر والتقدير لكم؛ لتعاونكم وتجاوبكم معنا.**
