### ISSUE TITLE
Disable Upload

### ISSUE THREAD

**Issue by Wenbyn** [awssat/kleeja#3]
Helo,

In the admin panel I see that there is no option for disable only upload.
So I want to everyone work on the website but that the upload was disables.

As I said before, the option to turn off the upload i can not be seen in the admin panel.
Will this option exist in a new version of kleeja?

**Comment by jaafer77** [comment]
what i understand from you that you want option to turn off the upload but
the download stays on correct? now kleeja doesnt supported by the owners so
we need to learn and do it by our selvies

في أربعاء، ٢٤ كانون الثاني، ٢٠١٨ في ٩:٢٦ م، كتب Wenbyn <
notifications@github.com>:

**Comment by abdumu** [comment]
remove all guest extensions.

**Comment by Wenbyn** [comment]
Thanks for yours answers.
I guess you'll embed this option (disable upload) in the next kleeja version.
