### ISSUE TITLE
 مشكلة عند تسجيل عضوية جديدة

### ISSUE THREAD

**Issue by momkin** [awssat/kleeja#4]
مرحباً توجد مشكلة اثناء تسجيل عضوية جديدة بالسكربت

يضهر الخطأ الثالي !
 click to Refresh this page ...
Sorry , There is an error in mysql , error : Error In query
[1064 : ]

Script: Kleeja
Kleeja Website

**Comment by jaafer77** [comment]
هذا الخطأ يمكنك اصلاحه من ملف ucp.php في السطر 235

في أحد، ٢٨ كانون الثاني، ٢٠١٨ في ٩:٢٨ م، كتب momkin <
notifications@github.com>:

**Comment by zakisoft2015** [comment]
انا اشترى اضافات منين للاسكربت

**Comment by 0nader** [comment]
الى الان ننتظر حل لهذا المشكلة

لاكن يوجد حل من المبرمجين

**Comment by jaafer77** [comment]
ماعي المشكلة؟

في ثلاثاء، ٣٠ كانون الثاني، ٢٠١٨ في ١:٠٥ م، كتب 0nader <
notifications@github.com>:

**Comment by 0nader** [comment]
قم بالتسجيل لتشاهد المشكلة
https://www.up4.cc/ucp.php?go=register

**Comment by abdumu** [comment]
اما ان لديك تعديلات او نسختك قديمة. 
النسخة الحالية لايوجد فيها هذه المشكلة

**Comment by 0nader** [comment]
لايوجد اي تعديلات ونسختي الاصدار الاخير
2.3

وتم رفع نسخة جديدة وربطها بقاعدة البيانات
ونفس المشكلة

**Comment by jaafer77** [comment]
مشكلة في ملف ucp  اصلحه ويرجع كل شي طبيعي

في ثلاثاء، ٣٠ كانون الثاني، ٢٠١٨ في ١٠:٢٨ م، كتب 0nader <
notifications@github.com>:

**Comment by 0nader** [comment]
ماتوقع المشكلة من ملف ucp 
اتوقع المشكلة من قاعدة البيانات

لان ركبت نسخة جديدة وشتغلت بدون اي مشكلة

لكن اذا قمت بربط النسخة مع قاعدة البيانات السابقة يخرب التسجيل

**Comment by jaafer77** [comment]
كانت عندي وحليتها من ucp  ولاتجد لها حلها لو لفيت جوجل كله

في ثلاثاء، ٣٠ كانون الثاني، ٢٠١٨ في ١٠:٥٦ م، كتب 0nader <
notifications@github.com>:
