### ISSUE TITLE
How to Transfer Files to Another Server

### ISSUE THREAD

**Issue by Wenbyn** [awssat/kleeja#40]
Hi,

Take for example that my website has a kleeja script installed and website is called http://website.com
Is it possible when someone upload file on http://website.com which is located on the 'server number 1' that it file is uploaded to 'server number 2' to my subdomain, for example http://001.website.com
and to be a download link something like this:
http://001.website.com/do.php?filename=a7e0281413171.rar

This question I asked because I have too many files on the 'server number 1' and for that I think open the subdomain and I want to place new upload files on the subdomen (server number 2).

Thank you in advance for your reply.

**Comment by munjoob** [comment]
i can add multi ftp server function to kleeja if @abdumu  not add ftp plugin soon
we will wait @abdumu

**Comment by abdumu** [comment]
@munjoob thanks bro. It's coming next month as a plugin.

**Comment by Wenbyn** [comment]
I did not mean 'ftp upload' , I mean 'web upload'.

Is it possible when someone upload file on http://website.com which is located on the 'server number 1' that it file is uploaded to 'server number 2' to my subdomain for example http://001.website.com

So I mean all the time on web upload !

**Comment by Wenbyn** [comment]
> I did not mean 'ftp upload' , I mean 'web upload'.
> 
> Is it possible when someone upload (web upload) file on http://website.com which is located on the 'server number 1' that it file is uploaded to 'server number 2' to my subdomain for example http://001.website.com
> 
> So I mean all the time on web upload !

Please, can anybody answer my question?
