### ISSUE TITLE
استفسار عن اضافة advanced extras

### ISSUE THREAD

**Issue by MitanOmar** [awssat/kleeja#45]
عند تثبيت الاضافة و كتابة هيدر او فوتر اضافي على اي صفحة  ثم حذف الاضافة ، تترك الاضافة بعض المخلفات في قاعدة البيانات .  
هل هناك داع ل بول ركويست جديد ؟

**Comment by abdumu** [comment]
هناك مقصد من ذلك، كي لا يفقد المستخدم ماكتب وهناك فواصل بينها.

لكن اذا كان لديك حل افضل فتفضل.

**Comment by MitanOmar** [comment]
في كلا الحالتين . فأن تلك المخلفات تظهر على جميع صفحات الموقع . ويحتاج المستخدم الى الكتابة من جديد . ساعمل بول ركويست و انت انظر الى الكود و الامر عائد لك في قبوله او تركه كما هو . شكرا ..
