### ISSUE TITLE
اذن لرفع اضافة

### ISSUE THREAD

**Issue by MitanOmar** [awssat/kleeja#48]
قمت ببرمجة إضافة لكليجا و اود ان ارفعها ضمن حزمة كليجا إذ رأيت إنها فعالة و عملية

الاضافة تقوم بالتحقق من اصدار الاضافات الموجودة في الاستضافة و بين الموجودة على غيت هوب
مع التنبيه اذا كانت الاضافة موجودة ضمن حزمة كليجا المعتمدة على غيت هوب او لا

طبعا لعدم وجود خريطة تبين المجلدات و الملفات ضمن حزمة كليجا على غيت هوب ( على ما اظن ) 
كان من الممكن تضمين اعدادات اكثر تقدما مثل تنزيل النسخة الاخيرة من التطبيق تلقائيا .
ولك جزيل الشكر

**Comment by MitanOmar** [comment]
<div dir="rtl" style="text-align: right;" trbidi="on">
<div class="separator" style="clear: both; text-align: center;">
<a href="https://4.bp.blogspot.com/-NyZ6M_N0S-Y/XDfLfbqsbpI/AAAAAAAAhvA/YVUJWVoQbQg-0OyI9N3bt2HjTHlt1tV5QCLcBGAs/s1600/screenshot.png"href="https://www.blogger.com/null" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="768" data-original-width="1366" src="https://4.bp.blogspot.com/-NyZ6M_N0S-Y/XDfLfbqsbpI/AAAAAAAAhvA/YVUJWVoQbQg-0OyI9N3bt2HjTHlt1tV5QCLcBGAs/s1600/screenshot.png" /></a></div>
<br /></div>

**Comment by MitanOmar** [comment]
screenshot : https://4.bp.blogspot.com/-NyZ6M_N0S-Y/XDfLfbqsbpI/AAAAAAAAhvA/YVUJWVoQbQg-0OyI9N3bt2HjTHlt1tV5QCLcBGAs/s1600/screenshot.png

**Comment by abdumu** [comment]
فكرة ممتازة،

بالنسبة لسوالك عن كيفية جلب خريطة تبين حزمة الاضافة الحالية في مستودع الكود فهذا مثال:
https://api.github.com/repos/awssat/kleeja/contents/plugins/kj_meta_seo


ارفع الاضافة

**Comment by MitanOmar** [comment]
check my page

**Comment by MitanOmar** [comment]
test the plugin , and say to me if you want me to upload it to kleeja or not ,
or adding it to kleeja script , like a part of system ,
befor 1 hour i add new option in the plugin , 
check line 32 in init.php
and say top my your openion :-)
best regards

**Comment by abdumu** [comment]
ساقوم بتجربتها، 

قمت بقراءة الاكواد مبدئيا واعجبني مارأيت خصوصا فحص الاصدار من رابط.

اذا اعتقدت انك وصلت لنسخة مكتملة من الاضافة قم بعمل بول ريكويست.

**Comment by MitanOmar** [comment]
ok

**Comment by MitanOmar** [comment]
i need some time to make my final idea , i can not work for next 2 weeks
i uploaded it for the developers , if they have another idea

**Comment by abdumu** [comment]
It's ok. I'll keep the PR open so you can add your changes to it anytime.

**Comment by MitanOmar** [comment]
مرحبا @abdumu
الرابط الذي اعطيتني إياه لديه 
Rate limit .
هل هناك حل لهذه المشكلة ؟

**Comment by abdumu** [comment]
caching?

**Comment by MitanOmar** [comment]
مممم سيزيد من التعقيدات التي لا داعي لها .
خاصة انه واجهتني بعض المشاكل و اضطررت ان اعيد البرمجة من الصفر اكثر من مرة . 
ساحاول ان اجد طريقة اخرى . و ان عجزت عنها ، ساعتمد على الكاش

**Comment by MitanOmar** [comment]
good morning @abdumu 
finally i done from the plugin
plugin name : plugins_updater
link : https://github.com/MitanOmar/plugins_updater
check the plugin , and i am waiting  your openion befor PR
best regards
:)
