### ISSUE TITLE
انا اشترى اضافات منين للاسكربت

### ISSUE THREAD

**Issue by zakisoft2015** [awssat/kleeja#5]
السلام عليكم

اريد شراء اضافات لاسكربت كيلجا

انا اشترى اضافات منين للاسكربت

**Comment by jaafer77** [comment]
عبد الرحمن قفل المتجر
لكن في مبرمج في خمسات يبرمج اضافات كليجا فقط

في ثلاثاء، ٣٠ كانون الثاني، ٢٠١٨ في ١٠:٢٢ ص، كتب zakisoft2015 <
notifications@github.com>:

**Comment by abdumu** [comment]
ليست مشكلة

**Comment by fileiraq** [comment]
سأقوم بوضعها في قسم المشاكل حتى تقومون بحلها
