### ISSUE TITLE
error in persian or arabic name file

### ISSUE THREAD

**Issue by dailymobile** [awssat/kleeja#53]
i apload 1 file with name کلیجا but after upload was name is DA%A9%D9%84%DB%8C%D8%AC%D8%A7
http://up.dailymobile.ir/uploads/guest/Screenshot-12-.png

**Comment by abdumu** [comment]
what is the file name, copy it here.

**Comment by dailymobile** [comment]
help @abdumu

**Comment by lamjed001** [comment]
me too the same error
%D9%84%D9%88%D9%82.zip

الإسم الأصلي | original name
لوق.zip

test to decode name here
https://www.urldecoder.org/

@abdumu add url decoder and will show the original name

**Comment by abdumu** [comment]
Is this happening only in download page?

**Comment by dailymobile** [comment]
`dl2.dailymobile.ir/12/kleeja-3.0.2/`
you can test 
when up and page download

**Comment by lamjed001** [comment]
@abdumu not only download page
it's on all pages
in admin panel
![image](https://user-images.githubusercontent.com/23016064/52395345-0cdd0c00-2aae-11e9-9a45-f449609efa9f.png)
and fileuser
![image](https://user-images.githubusercontent.com/23016064/52395388-372ec980-2aae-11e9-8b0c-8f5ae01b2bea.png)
so the name encoded if you upload an file with arabic name

**Comment by abdumu** [comment]
thank you for reporting .. will be fixed in the next version

**Comment by abdumu** [comment]
@MitanOmar  is this happening to you? I can not reproduce
