### ISSUE TITLE
مشكل الربط مع vbulletin 5

### ISSUE THREAD

**Issue by saiffon** [awssat/kleeja#54]
السلام عليكم
حاولت الربط مع منتدى في بي 5 فظهرت لي هذه المشكلة
Forum path is not correct
مسار السكربت vbulletin الذي تم ربط عضويات كليجا معه خاطئ، قم بضبطه

**Comment by abdumu** [comment]
وين مسار الكونفق داخل الفي بي

**Comment by saiffon** [comment]
Vb/core/includes/config

**Comment by abdumu** [comment]
اضف التالي للكونفق

```define('SCRIPT_CONFIG_PATH', '/core/includes/config.php');```

**Comment by saiffon** [comment]
وضعته بهذا الشكل لكن عند محاولة الدخول لااستطيع لاببيانات المنتدى ولاببيانات السكربت

يظهر لي هذا الخطا

خطأ.. لا يمكن الدخول!


$dbprefix		= 'klj_'; // if you use prefix for tables , fill it 


#for integration with other scripts 
define('SCRIPT_CONFIG_PATH', '/core/includes/config.php');
$script_path = '../vb';// 

$script_cp1256    = true; 
$script_encoding = 'utf-8';// 
$script_srv = 'localhost';

**Comment by abdumu** [comment]
جرب ازالة 
$script_cp1256 = true;
و 
$script_srv = 'localhost';

**Comment by saiffon** [comment]
نفس المشكل للاسف

هل يمكن الربط عبر ال api

**Comment by abdumu** [comment]
اخر تجربة اضافة
$script_db_charset = 'utf8';

ان لم يعمل فحتى الاباي لايفيدك لان نظام العضويات قد يكون تغير في في بي ٥ ويحتاج اعادة كتابة في كليجا.

**Comment by saiffon** [comment]
بالفعل تغير مقارنة مع الاجيال القديمة

هل يمكنك مدنا بالمتغيرات التي نحتاجها في الربط بواسطة api ?

**Comment by abdumu** [comment]
هذا موضوع قديم للاباي وهو ايضا قديم لم يتم تحديثه لاخر نسخة في بي

http://www.moffed.com/community/viewtopic.php?f=37&t=5416

عندما اجد الوقت لتجربة في بي ٥ واجد نسخة استطيع تركيبها على خادمي المحلي ساجرب. 

بالتوفيق
