### ISSUE TITLE
admin check update without message

### ISSUE THREAD

**Issue by lamjed001** [awssat/kleeja#56]
![image](https://user-images.githubusercontent.com/23016064/52395529-deabfc00-2aae-11e9-9d67-3841d1bf946d.png)
Kleeja Version : f0dac81b089845c31012604493104787ac60e52d

This error appears after this update : https://github.com/awssat/kleeja/commit/c565d4f8df4e4b142728170fc4adc93091d54d55

**Comment by abdumu** [comment]
thank you ..

**Comment by lamjed001** [comment]
same error not work :(
