### ISSUE TITLE
تطوير رفع الملفات

### ISSUE THREAD

**Issue by LIONHAERT** [awssat/kleeja#57]
مرحبا اخواني يرجى تتطوير شريط انتظر رفع الملفات إلى رقمي يكون عداد رقمي وسرعة الملفات يكون السكربت جاهز من من كل شي واضافة سحب ملفات من اي موقع إذا كان فيديو او ملف 
 iframe عادي واضافة عند رفع  للفيديو

**Comment by abdumu** [comment]
استخدم ستايل دراق دروب

**Comment by LIONHAERT** [comment]
اخي انظر إلى باقي الطلبات
