### ISSUE TITLE
اضافة جديدة

### ISSUE THREAD

**Issue by rikojilani** [awssat/kleeja#68]
قمت بتطوير اضافة لكليجا
أرجو الاطلاع عليها ان كانت مناسبة للرفع
*****

**Comment by MitanOmar** [comment]
There is an error in zip file . Can not open it

**Comment by MitanOmar** [comment]
هل بامكانك رفع الشفرة الى غيت هب ؟

**Comment by abdumu** [comment]
هناك خطا بملف الارشيف، اعد ضغط الملفات وارفعه

**Comment by nicolasnoble** [comment]
This is a malware.

**Comment by abdumu** [comment]
@nicolasnoble Thanks.
you are right, I'm on MacOS and it's only appears as corrupted archive.

https://www.virustotal.com/#/file/2697c9e38d1e081c8fa5f07db8e1500c0f90dca4f408e1b582f8f00c8ade9c52/detection
