### ISSUE TITLE
bootstrap 4.3 update error's

### ISSUE THREAD

**Issue by lamjed001** [awssat/kleeja#69]
errors
![capture](https://user-images.githubusercontent.com/23016064/53635439-6ce25080-3c1d-11e9-950c-e0d424b5cb2e.PNG)

Bug with Bootstrap Black
![capture2](https://user-images.githubusercontent.com/23016064/53635444-6eac1400-3c1d-11e9-816d-ad3b18f55649.PNG)

**Comment by abdumu** [comment]
جرب تسوي حذف للكاش في المتصفح

![](https://www.getfilecloud.com/blog/wp-content/uploads/2015/03/Hardrefresh-chrome.png)

**Comment by lamjed001** [comment]
> جرب تسوي حذف للكاش في المتصفح
> 
> ![](https://camo.githubusercontent.com/8e04aa09aa86da26d715fff25d5e34deffc04626/68747470733a2f2f7777772e67657466696c65636c6f75642e636f6d2f626c6f672f77702d636f6e74656e742f75706c6f6164732f323031352f30332f48617264726566726573682d6368726f6d652e706e67)

نفس المشاكل :(

**Comment by abdumu** [comment]
ستايل بوستراب بلاك يعتمد على ساتيل بوستراب ، تاكد انك حدثتهم جميعهم لاخر نسخة باالريبو وجرب اللي فوق

**Comment by lamjed001** [comment]
كل شي تمام المشكل مني اسف
