### ISSUE TITLE
أخر استعراض + احصائيات المركز لاتظهر

### ISSUE THREAD

**Issue by 0nader** [awssat/kleeja#7]
السلام عليكم ورحمة الله وبركاتة

يوجد لدي مشكلة وهي ان

أخر استعراض + احصائيات المركز 

في لوحة التحكم لاتظهر

هل يوجد طريقة لأظهارها

هذا صورة للمشكلة
http://up4.cc/do.php?img=48575

شاكر لكم

**Comment by abdumu** [comment]
تظهر بعد عدة ايام من الاستخدام
