### ISSUE TITLE
مشكلة التحقق من رقم الاصدار

### ISSUE THREAD

**Issue by munjoob** [awssat/kleeja#8]
بعد تحديث موقع كليجا الجديد لم يعد يصل تبليغ بالاصدار الجديد من خلال لوحة التحكم
يجب تأمين بديل

**Comment by abdumu** [comment]
استخدم اخر نسخة وراح تشوف ان كليجا تجلب الاصدار من هنا، قيت هب. راجع الكود.

**Comment by munjoob** [comment]
زميلي أرجو أن تقبل نقدي
يجب أن يكون هناك معايير حقيقة أثناء تطوير السكريبت 
أغلب أصحاب المواقع لا يعلمون بظهور تحديث  إلا من خلال لوحة التحكم يجب ترك ملف بالموقع القديم ريثما ينتقل أغلب المستخدمين للإصدار الجديد
