### ISSUE TITLE
السكربت

### ISSUE THREAD

**Issue by leech24** [awssat/kleeja#80]
اولا اشكرا القائمين على سكربت كليجا
فهو فعلا مميز

المشكلة كالتي
السكربت لا يظهر الصور بالتمبلت
حتي لو فتحت صور التملبت مباشرة لا تظهر
رغم وجود التصاريح 777

مواصفات السرفر
php7
اخر اصدار من قاعدة البيانات

**Comment by abdumu** [comment]
احذف الستايل وارفعه من جديد، واذا كنت تستخدم 
ssl 
تاخذ من وضع الرابط صح في لوحة التحكم مع هتبز

**Comment by sarhandev** [comment]
Why iam replying on it ?
To add some information about the Issue.
----
Make sure to clear cache to show it, if you are using Cloudflare you can make Page Rule to bypass the cache.
